import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import StoryBlokProvider from "@/components/StoryBlokProvider";
import DefaultLayout from "@/components/sb/DefaultLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params, ...props }) {
  const {lang} = await params
  console.log("LANG", lang)
  return (
    <StoryBlokProvider>
      <html lang={lang}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <DefaultLayout lang={lang}>{children}</DefaultLayout>
        </body>
      </html>
    </StoryBlokProvider>
  );
}
