import { Geist, Geist_Mono } from "next/font/google";
import "../../../globals.css";
import StoryBlokProvider from "@/components/StoryBlokProvider";
import DefaultLayout from "@/components/sb/DefaultLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function BlogPageLayout({ children }) {
  return (
    <StoryBlokProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <DefaultLayout withFooter={false}>{children}</DefaultLayout>
        </body>
      </html>
    </StoryBlokProvider>
  );
}
